services:
  - redis-server
  - postgresql

tasks:
  - flake8
  - isort -c -rc frigg
  - tox
  - coverage report --fail-under=90
  - coverage xml
 
deploy_tasks:
  - pip install gunicorn -r requirements/base.txt
  - make frigg/settings/local.py
  - createdb frigg
  - python manage.py migrate
  - python manage.py loaddata frigg/builds/fixtures/users.json
  - python manage.py loaddata frigg/builds/fixtures/test_views.yaml
  - python manage.py collectstatic --noinput
  - gunicorn -D -b 0.0.0.0:8000 frigg.wsgi

verbose_tasks:
  - coverage report --fail-under=90

coverage:
  path: coverage.xml
  parser: python

deployment:
  image: frigg/frigg-test-base
