services:
  - redis-server
  - postgresql

tasks:
  - flake8
  - isort -c -rc frigg
  - tox
  - coverage report --fail-under=90
  - coverage xml

verbose_tasks:
  - coverage report --fail-under=90

coverage:
  path: coverage.xml
  parser: python
