services:
  - redis-server
  - postgresql

tasks:
  - flake8
  - isort -c -rc frigg
  - tox
  - coverage report --fail-under=90
  - coverage xml
 
deploy_tasks:
  - pip install -r requirements/base.txt
  - make frigg/settings/local.py
  - createdb frigg
  - python manage.py migrate
  - python manage.py collectstatic --noinput
  - python manage.py runserver 0.0.0.0:8000

verbose_tasks:
  - coverage report --fail-under=90

coverage:
  path: coverage.xml
  parser: python

deployment:
  image: frigg/frigg-test-base
